APP_NAME: pistahx_app
ENV_NAME: production
ELK_SERVER: to be defined
JWT_SECRET: prod_secret_key
JWT_TTL: 3600
CACHE_OUT_TTL_DEFAULT: 60
GOOGLE_CLIENT_ID: to be defined
GOOGLE_CLIENT_SECRET: to be defined
GOOGLE_CALLBACK_URL: http://host to be defined/callback
REDIS_HOST: to be defined
REDIS_PORT: 6379
DB_HOST: to be defined
DB_USER: to be defined
DB_PASSWORD: to be defined
DB_NAME: to be defined
DB_OPTIONS:
  host: to be defined
  dialect: mssql
  pool: 
    max: 5
    min: 0
    idle: 10000
  dialectOptions: 
    encrypt: true
  logging: false
SESSION_TTL: 3600
BASE_URL: /api/v1
API_PORT: 8081;
API_ROUTE_STATUS: /users/me/status
#API_CORS_ALLOWED:
#  - "http://localhost:9000"
#  - "http://localhost:8080"
#  - "http://localhost:3000"
#S3_ID: "to be defined"
#S3_KEY: "to be defined"
#S3_BUCKET: "to be defined"
#S3_REGION: "to be defined"
#S3_FOLDER: "to be defined"